### ISSUE TITLE
Navigation: Go contactless hero image goes in front of nav, should go behind

### ISSUE THREAD

**Issue by calexity** [cal-itp/transit-stop#128]
1) Can the hero illustration on the "Tap into the future of fare payment" go behind the nav?
Screenshot: https://www.dropbox.com/s/7btbwc9yseihcof/Screen%20Shot%202021-01-04%20at%202.36.18%20PM.png?dl=0

2) Can you remove the extra space between the nav and the hero section?
Screenshot: https://www.dropbox.com/s/4z9ah06rozr3ebs/Screen%20Shot%202021-01-04%20at%202.37.47%20PM.png?dl=0

**Comment by krainboltgreene** [comment]
Ugh, yeah, this is why I hate z-indexing.

**Comment by krainboltgreene** [comment]
Re 2, looks like it was explicitly added at some point?
