### ISSUE TITLE
Contact form: Standardize phone number input

### ISSUE THREAD

**Issue by calexity** [cal-itp/transit-stop#131]
Phone number box should be standardized, either strip special characters or just allow numbers, etc.

Can you advise on what hubspot expects when that form is submitted?

**Comment by krainboltgreene** [comment]
The current input is the html standard `tel`, is it not allowing characters?

**Comment by calexity** [comment]
@krainboltgreene it's going to allow for anything. I could write a novel in there. This is going to make the data a mess on the other side. Are there limits on the hubspot side? If not, can we restrict to 10 digits and numbers only?

**Comment by krainboltgreene** [comment]
Yeah, that's the approach W3 took since numbers vary pretty wildly. I don't know what hubspot's limits are, I've never used hubspot.

What internationalization are we limiting to?

**Comment by calexity** [comment]
@krainboltgreene I'm pretty sure we should just take US-based numbers as this is for California but @vykster @esquared415 any input on this?

**Comment by vykster** [comment]
Don't worry about Hubspot. We don't plan to internationalize this site. Yes, let's limit to US phone numbers.

**Comment by krainboltgreene** [comment]
KK, just a reminder that people who live in the US can have non-us numbers. I'll limit it to 11 digits.
