### ISSUE TITLE
Go contactless: Mobile layout

### ISSUE THREAD

**Issue by calexity** [cal-itp/transit-stop#133]
The mobile layout for the go contactless page needs to be completed.

See mock here: https://www.figma.com/file/QR2c1HOhrJptQbN0FSfu9J?node-id=2045:3758#56050246

Current screenshots: 
https://www.dropbox.com/s/jpuf72gw7lk14ni/IMG_8364.PNG?dl=0
https://www.dropbox.com/s/2nislw6wa0713fh/IMG_8365.PNG?dl=0
https://www.dropbox.com/s/xplnv0khnn3178w/IMG_8366.PNG?dl=0

**Comment by krainboltgreene** [comment]
See also #123
