### ISSUE TITLE
Page template: Ability for content team to upload images

### ISSUE THREAD

**Issue by calexity** [cal-itp/transit-stop#190]
As the content team,
When I am creating a page,
I want to be able to add images
and caption them

--
This story includes
- Uploading images to the CMS
- Ability to place or move the image in the page
- Ability to add alt text
- Ability to caption the image

**Media storage**
- Need to determine where files are stored (images, pdfs, etc)

**Design in Figma (see Design 1.1 Release)**
https://www.figma.com/file/QR2c1HOhrJptQbN0FSfu9J/Mobility-Marketplace?node-id=2330%3A9477

**Comment by vykster** [comment]
Start with identifying options and prices for file storage
