### ISSUE TITLE
Page template: Ability for content team to style text and links

### ISSUE THREAD

**Issue by calexity** [cal-itp/transit-stop#191]
As the content team,
When I am creating a page
I want to be able to style the text within the page
So the piece is easier to scan and read

--

This story includes
- Ability to select text and style as H1-H5 or Paragraph
- Ability to add a link to a piece of text
- Ability to underline text
- Ability to italicize text
- Ability to bold text

**Design in Figma (see Design 1.1 Release)**
https://www.figma.com/file/QR2c1HOhrJptQbN0FSfu9J/Mobility-Marketplace?node-id=2330%3A9477

**Comment by vykster** [comment]
Team will be using markdown to style text, see: https://guides.github.com/features/mastering-markdown/
