### ISSUE TITLE
Page template: Ability for content team to publish a basic page

### ISSUE THREAD

**Issue by calexity** [cal-itp/transit-stop#195]
As the content team,
I want to be able to create a new page
So that I can write and public basic site info like About and Glossary
And share it with transit providers or others via a unique link

----
This story includes

- A way for content team to add a new page via the CMS
- Ability to title the page
- Ability to write or edit the URL path
- Ability to add plain text content to the body of the page, in markdown
- Ability to publish the page and view it by going to the unique link

**Resources**
- [Design in Figma (see Design 1.1 Release)](
https://www.figma.com/file/QR2c1HOhrJptQbN0FSfu9J/Mobility-Marketplace?node-id=2330%3A9477)
- [Netlify CMS Docs](https://www.netlifycms.org/docs/intro/)
- [New Content from content team](https://docs.google.com/document/d/1cAE3gjMVUQLKufr4f3B1pxHGqERy1nVQJta__oibG8s/edit)

**QA**
- Kurtis will get to PR, which will include a deploy preview link
- @calexity will assist Harrison and Jess in accepting the completed story

**Comment by vykster** [comment]
Kurtis needs to review CMS documentation before beginning work.

**Comment by vykster** [comment]
https://www.netlifycms.org/docs/intro/

**Comment by krainboltgreene** [comment]
Looks like I need to setup blank pages to be navigated to.
