### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by calexity** [cal-itp/transit-stop#20]
@thekaveman Set up a GA account under our Compiler one. Here's the code:

UA-176840950-1

**Comment by calexity** [comment]
PS that's for production - do you want one for staging? Is that hard to switch or should we just deal with some noise from dev/staging?

**Comment by thekaveman** [comment]
Thanks for this @calexity! 

Good question on prod vs. stage. We're working on the domain stuff right now; if we're able to use Netlify's DNS management features, we can have a [separate subdomain for staging](https://docs.netlify.com/domains-https/custom-domains/multiple-domains/#branch-subdomains). This should allow us to at least filter out staging vs. prod traffic in GA. I will also look into the ability to configure different GA for different environments in Netlify.
