### ISSUE TITLE
Get the contact form submissions into CRM (Hubspot) and to newsletter platform (Constant Contact)

### ISSUE THREAD

**Issue by calexity** [cal-itp/transit-stop#201]
We need a way for Erika, Harrison or Jess - or a person they designate - to be able to check or receive the information submitted on the Mobi Mart contact form.

We'd like to
- Subscribe them to newsletter (Constant Contact)
- Add to CRM with a tag (Hubspot integration)

**Comment by vykster** [comment]
Let's scope this around what we are going to do with the form submissions. 

ie: every two weeks the emails will be added to the email distro list, uploaded to CRM and tagged.

**Comment by calexity** [comment]
Questions/action steps that need to be resolved for Kurtis to work on this:

- Access to Hubspot and Constant Contact
- What fields go to which tool (email and role? or name also?)
- What the tag is for Hubspot
- A point person for Hubspot and Constant Contact who will be using this info so Kurtis can show them and ask questions

@vykster @krainboltgreene

**Comment by thekaveman** [comment]
FYI we now have the Contact form submitting tickets to our Desk inbox, via a Zapier integration. Can probably close this out?

**Comment by vykster** [comment]
Yes!
