### ISSUE TITLE
Technical exploration: options for PDF storage

### ISSUE THREAD

**Issue by calexity** [cal-itp/transit-stop#202]
The content team will need to be able to upload a PDF and allow readers to download the PDF. In the future, we may want to embed/display that PDF, but for now download is the first goal.

This ticket is for a technical investigation into options for storing those PDFs.

**Comment by krainboltgreene** [comment]
Anything uploaded to netlify admin gets stored in github which can be accessed via `http://{{site}}/assets/upload/{filename}`.
