### ISSUE TITLE
Update text on MobiMart homepage

### ISSUE THREAD

**Issue by harrisonpeck** [cal-itp/transit-stop#260]
We need to add a couple sentences to the MobiMart homepage on the morning of Wednesday, April 21. This is timed to coincide with Cal-ITP's presentation at the CALACT conference on Wednesday so needs to happen no sooner and no later than Wednesday morning. We'll be announcing the release of the RFPs for the transit processor and fare validators and including a link to the DGS website to access the documents. However, DGS will not be posting this until Wednesday morning, so unfortunately the link will not be available until you're ready to publish. I will add a comment to this ticket with the URL when it is live, then it'll be a quick turnaround time.

Below is a screenshot to where on the homepage this should go. And here is what the text should read (note that I will likely revise based on Gillian feedback early next week):

----

## Payment system RFP, hot off the press!

California just moved one big step closer to contactless fare collection with the release of a draft [Request for Proposals (RFP)](https://caleprocure.ca.gov/event/77601/0000019394) for fare validators and fare calculation software (transit processor). Visit the Department of General Services (DGS) to view the notice of availability.

![image](https://user-images.githubusercontent.com/80477201/115061264-f36a5280-9eb6-11eb-9afb-c93214277b4f.png)

**Comment by harrisonpeck** [comment]
Hi guys! Here's the link: https://caleprocure.ca.gov/event/77601/0000019394. Please add to the site 9am PDT today. 

And slightly tweaked text, please use this:

California just moved one big step closer to contactless fare collection with the release of [draft requests for proposals](https://caleprocure.ca.gov/event/77601/0000019394) for fare validators and fare calculation software (transit processor). Visit the Department of General Services (DGS) to view the notice of availability.

**Comment by harrisonpeck** [comment]
Ah one more tweak: please make it "request for proposal" not "requests for proposal" (singular not plural).

**Comment by harrisonpeck** [comment]
Sorry one more tweak: Instead of "draft requests for proposals", please write it as "draft Request for Proposals (RFP)", and hyperlink the words "Request for Proposals (RFP)". Important that the word "Request" is singular, not plural, and that R and P are capitalized. Thanks!!

**Comment by thekaveman** [comment]
@krainboltgreene @allejo updated the text with final version.

**Comment by thekaveman** [comment]
Closed by #261
