### ISSUE TITLE
Mobile version of Homepage: RFP section is hidden

### ISSUE THREAD

**Issue by esquared415** [cal-itp/transit-stop#262]
![image](https://user-images.githubusercontent.com/50693483/115895405-3aa09800-a40f-11eb-9185-ed2c7e054e2f.png)

The "Payment system RFP, hot off the press!" text block is visible on the Desktop version of the website, but it's hidden on the Mobile version. 

Please push that section onto Mobile version. 

Thanks!

**Comment by allejo** [comment]
Closed in #264
