### ISSUE TITLE
Temporary content reorganization

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/transit-stop#271]
Ahead of the larger changes slated for the Summer, we want to make MobiMart's information around the state of available contracts more available. Current language lives on the [Contact Us](https://www.camobilitymarketplace.org/contact) page, but this is unintuitive for new visitors and strange for folks directed there. We need to create a new page (tentatively, Contracts) to showcase that information. 

The following changes are needed:

## [Contact us](https://www.camobilitymarketplace.org/contact) page

1. Remove the intro paragraph
1. Remove the three product blocks under the intro paragraph
1. Remove the form header
1. Raise the form intro into the page intro
1. Add email newsletter signup link

```diff
## Cal-ITP is here to help

- Cal-ITP can connect you with pre-procured, competitively bid contracts at competitive rates to help you modernize
- your transit system. To start the switch to contactless fare collection, you’ll need just three things:

- ### Payment processor
-
- Back-end service that transmits fares from riders’ bank cards and smart devices to transit providers’ bank accounts.
-
- Current vendors: Elavon, Fiserv
-
- Questions? Contact Cal-ITP using the form below.
-
- ### Fare calculation software
-
- Recognizes riders’ unique payment methods and charges the best fare for each trip, accounting for applicable discounts
- and distance traveled. It also enables “fare capping,” meaning that riders will no longer be charged for additional
- trips after reaching the cost of an unlimited pass.
-
- Current vendors: View the draft RFP
-
- ### Fare validators
-
- On-board or platform devices equipped with NFC and cEMV technology to read and validate riders’ contactless
- bank cards and smart devices.
-
- Current vendors: View the draft RFP
-
- ## Get in touch

Complete the below form, and someone from the Cal-ITP team will reach out soon to get you started with vendor
selection, pricing, and procurement—or just to respond to your comment or question.
+ 
+ You can also [sign up for our mailing list](link) for updates on newly available products and services.
```

## Contracts (new)

1. Create a new page under the URL `/contracts`.
1. Add the deleted product blocks from the Contact us page.

```diff
+ To start the switch to contactless fare collection, you’ll need just three **things:**
+
+ ### Payment processor
+
+ Back-end service that transmits fares from riders’ bank cards and smart devices to transit providers’ bank accounts.
+
+ Current vendors: Elavon, Fiserv
+
+ Questions? Contact Cal-ITP using the form below.
+
+ ### Fare calculation software
+
+ Recognizes riders’ unique payment methods and charges the best fare for each trip, accounting for applicable discounts
+ and distance traveled. It also enables “fare capping,” meaning that riders will no longer be charged for additional
+ trips after reaching the cost of an unlimited pass.
+
+ Current vendors: View the draft RFP
+
+ ### Fare validators
+
+ On-board or platform devices equipped with NFC and cEMV technology to read and validate riders’ contactless
+ bank cards and smart devices.
+
+ Current vendors: View the draft RFP

```

## Navigation

1. Move **Glossary** from the top nav to the second position in the bottom nav (between **Back to top** and **Privacy policy**)
1. Add **View contracts** to the top nav between **Go contactless** and **Provider map**.

**Comment by thekaveman** [comment]
@harrisonpeck please comment with any corrections or updated language for any of these shorter-term changes.

**Comment by harrisonpeck** [comment]
Thanks! Let's make the navbar text read "View contracts". I like /contracts as the url though. 

Questions: Why do you propose moving text from the About page to Contact Us? I'd lobby to leave it as is, as this text has already been vetted and approved. And I think the Contact Us page should basically be a contact form, doesn't need much intro text.

The only other thing we'll need to do is make sure that any hyperlinks around the site (i.e. on the About page) are updated to direct users to the new /contracts page. I think I can mostly do that on my own but will identify each instance and send a list over in places not available for editing in the CMS.

**Comment by thekaveman** [comment]
@harrisonpeck:

> Questions: Why do you propose moving text from the About page to Contact Us? I'd lobby to leave it as is, as this text has already been vetted and approved.

Sorry, I must have misunderstood yesterday. I thought we wanted to take those few paragraphs that mention the newsletter and move them to Contact Us (no wording changes). Since Contact Us is more of an "action" page where we expect them to do something, vs. About being more of a plain info page. 

If I misunderstood then no worries! We don't have to change About.

The other thought I had was "Opportunities" instead of "Contracts" (and /opportunities) - not sure if that wording is correct, but it feels more welcoming than Contracts.

**Comment by harrisonpeck** [comment]
Hm, I guess we didn't totally land on a resolution for this. I think ultimately Contact Us should be for questions and comments. The email form on the bottom of each page in Kristi's mockup can be for contract updates and newsletter signup. But for this interim solution, I guess we just have one Contact page. What do you think the right "action" should be for this page? We can always just leave the text that's there ("Complete the form below...") for now.

**Comment by thekaveman** [comment]
@harrisonpeck I think you were right to suggest leaving About alone for the interim, until the bigger changes from @kristigrassi. I reformatted my original description to remove those changes, and with a diff view of the proposed text changes on the other pages. Does this seem good for the interim?

**Comment by harrisonpeck** [comment]
@thekaveman Yes! This looks correct to me. Thanks!!

**Comment by thekaveman** [comment]
@allejo we're good to go on these changes when you get a chance.

**Comment by allejo** [comment]
working on this right now :construction:
